### ISSUE TITLE
Unable to install `rprotobuf` with `libprotoc 28.3`

### ISSUE THREAD

**Issue by byrongibby** [eddelbuettel/rprotobuf#107]
Hi. I am having an issue similar (I think) to #92 

The error message I am getting is

```
DescriptorPoolLookup.cpp:35:24: error: cannot declare variable ‘rprotobuf::DescriptorPoolLookup::error_collector’ to be of abstract type ‘rprotobuf::RWarningErrorCollector’
   35 | RWarningErrorCollector DescriptorPoolLookup::error_collector;
      |                        ^~~~~~~~~~~~~~~~~~~~
In file included from DescriptorPoolLookup.h:8,
                 from DescriptorPoolLookup.cpp:22:
RWarningErrorCollector.h:7:7: note:   because the following virtual functions are pure within ‘rprotobuf::RWarningErrorCollector’:
    7 | class RWarningErrorCollector : public GPB::compiler::MultiFileErrorCollector {
      |       ^~~~~~~~~~~~~~~~~~~~~~
In file included from rprotobuf.h:37,
                 from DescriptorPoolLookup.cpp:21:
/usr/include/google/protobuf/compiler/importer.h:183:16: note:     ‘virtual void google::protobuf::compiler::MultiFileErrorCollector::RecordError(absl::lts_20240722::string_view, int, int, absl::lts_20240722::string_view)’
  183 |   virtual void RecordError(absl::string_view filename, int line, int column,
      |                ^~~~~~~~~~~
make: *** [/usr/lib64/R/etc/Makeconf:204: DescriptorPoolLookup.o] Error 1
```

I am on Arch Linux

```
libprotoc 28.3
gcc (GCC) 14.2.1 20240910
```

I do not have enough knowledge to confirm, but I am speculating that similar to #92 the issue has to do with a [breaking change in >= 26.0](https://protobuf.dev/news/v26/#remove-stdstring-error-collector-overrides)? If someone could confirm this or put me on the right path to getting the package installed I would be grateful. Thanks.

**Comment by eddelbuettel** [comment]
What OS are you on?  How did you try to install, and what did you try install, the CRAN version or the repo version?

Last time I updated the repo the CI (on Ubuntu) was happy, and CRAN has no issue either as can be seen on the [results page](https://cloud.r-project.org/web/checks/check_results_RProtoBuf.html).   (The 'please do not call SET_TYPEOF goes away if you use an Rcpp version newer than what CRAN has, eg from our repo or r-universe.)

Your error message brings up `absl` so that recent [PR #106](https://github.com/eddelbuettel/rprotobuf/pull/106) may help you, as may [PR #104](https://github.com/eddelbuettel/rprotobuf/pull/104).  So might be worth trying
```r
remotes::install("eddelbuettel/rprotobuf")
```

**Comment by byrongibby** [comment]
I am on Arch Linux, installing from GitHub rather than CRAN did indeed resolve the issue, thank you very much for pointing me in the right direction and for the speedy reply!

**Comment by eddelbuettel** [comment]
Excellent news.  

And yes -- with R packages it is often helpful to also try the git repo.  I will try to remember to get this updates at CRAN.
